name: NodeJS with Electron

on:
  push:
    branches: ["main", "feature/github-actions"]
  pull_request:
    branches: ["main", "feature/github-actions"]

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: feature/github-actions
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: see directory
        run: ls
  build_on_win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
        with:
          ref: feature/github-actions
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: see directory
        run: ls

  # build_on_linux:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Build
  #       run: |
  #         npm install
  #         npx webpack
