name: NodeJS with Electron

on:
  push:
    branches: ["main", "feature/github-actions"]
  pull_request:
    branches: ["main", "feature/github-actions"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: "linux", image: "ubuntu-latest" },
            { name: "windows", image: "windows-latest" },
            { name: "macos", image: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20
      - run: npm ci
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
# jobs:
#   build_on_mac:
#     runs-on: macOS-latest
#     steps:
#       - uses: actions/checkout@master
#         with:
#           ref: feature/github-actions
#       - uses: actions/setup-node@master
#         with:
#           node-version: 20.x
#       - name: see directory
#         run: ls
#       - name: Install Dependencies
#         run: npm install
#       - name: Build Project
#         run: npm run build
#       - name: Build Electron App
#         run: |
#           npx electron-forge import
#           npm run make
#   build_on_win:
#     runs-on: windows-2016
#     steps:
#       - uses: actions/checkout@master
#         with:
#           ref: feature/github-actions
#       - uses: actions/setup-node@master
#         with:
#           node-version: 20.x
#       - name: see directory
#         run: ls
#       - name: Install Dependencies
#         run: npm install
#       - name: Build Project
#         run: npm run build
#       - name: Build Electron App
#         run: |
#           npx electron-forge import
#           npm run make
#   build_on_linux:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x]
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           ref: feature/github-actions
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: see directory
#         run: ls
#       - name: Install Dependencies
#         run: |
#           sudo apt-get install fakeroot dpkg rpm -y
#           npm install
#       - name: Build Project
#         run: npm run build
#       - name: Build Electron App
#         run: |
#           npx electron-forge import
#           npm run make
