name: NodeJS with Electron

on:
  push:
    branches: ["main", "feature/github-actions"]
  # pull_request:
  #   branches: ["main", "feature/github-actions"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: "linux", image: "ubuntu-latest" },
            { name: "windows", image: "windows-latest" },
            { name: "macos", image: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npx electron-forge import
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
